language: node_js, java

node_js:
  - "node"

jdk:
  - oraclejdk8

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.9.0

cache:
  directories:
    - node_modules

install:
  - npm install
  - wget $URL/redpen-1.9.0.tar.gz
  - tar xvf redpen-1.9.0.tar.gz
  - export PATH=$PWD/redpen-*/bin:$PATH

script:
  - ls
  - redpen conf/redpen-conf-ja.xml source/_posts/*/*/*.md

after_success:
  - git config --global user.name "debugon"
  - git config --global user.email "games0421@gmail.com"
  - git init
  - hexo deploy -g
