language: node_js, java

node_js:
  - "node"

jdk:
  - oraclejdk8

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.9.0

install:
  - npm install
  - wget $URL/redpen-1.9.0.tar.gz
  - tar xvf redpen-1.9.0.tar.gz

script:
  - hexo deploy -g
