language: java

jdk:
  - oraclejdk8

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.9.0

install:
  - wget $URL/redpen-1.9.0.tar.gz
  - tar xvf redpen-1.9.0.tar.gz

script:
  - redpen-distribution-1.9.0/bin/redpen index.html
